name: Build

on:
  push:
    branches:
      - main
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - 'README.md'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '!.github/workflows/**'
      - 'README.md'

jobs:
  BuildISO:
    name: Build ISO
    runs-on: ubuntu-latest
    steps:
    - name: Clone tree
      uses: actions/checkout@v2
      with:
        submodules: recursive
        path: nxdk_vsh_tests
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          llvm \
          lld \
          libsdl2-dev \
          libsdl2-image-dev
        pip3 install nv2a-vsh

    - name: Prewarm nxdk
      working-directory: nxdk_vsh_tests
      run: |
        export CMAKE_POLICY_VERSION_MINIMUM=3.5
        ${GITHUB_WORKSPACE}/nxdk_vsh_tests/prewarm-nxdk.sh

    - name: Compile
      run: |
        cd nxdk_vsh_tests
        export NXDK_DIR="${GITHUB_WORKSPACE}/nxdk_vsh_tests/third_party/nxdk"
        cmake -B build \
              -DCMAKE_BUILD_TYPE=Release \
              -DCMAKE_TOOLCHAIN_FILE="${NXDK_DIR}/share/toolchain-nxdk.cmake"
        cmake --build build -- -j$(grep -c processor /proc/cpuinfo)

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nxdk_vsh_tests_xiso.iso
        path: nxdk_vsh_tests/build/src/xiso/nxdk_vsh_tests_xiso/nxdk_vsh_tests_xiso.iso

  CreateRelease:
    needs: [ BuildISO ]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - name: Clone tree
        uses: actions/checkout@v4
        with:
          path: nxdk_vsh_tests

      - name: Calculate version
        id: calculate-version
        run: |
          echo "version=$(date +'%Y-%m-%d_%H-%M-%S-%N')" >> $GITHUB_OUTPUT

      - name: Create tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          custom_tag: ${{ steps.calculate-version.outputs.version }}

      - uses: actions/download-artifact@v4
        with:
          name: nxdk_vsh_tests_xiso.iso
          path: .

      - name: Create release
        uses: softprops/action-gh-release@v2.2.1
        with:
          tag_name: ${{ steps.tag_version.outputs.new_tag }}
          name: "NV2A PGRAPH tests ${{ steps.tag_version.outputs.new_version }}"
          prerelease: false
          draft: false
          files: |
            nxdk_vsh_tests_xiso.iso


  BuildMacOS:
    name: Build macOS
    runs-on: macOS-latest
    if: github.event_name == 'pull_request'

    steps:
      - name: Clone tree
        uses: actions/checkout@v4
        with:
          submodules: recursive
          path: nxdk_vsh_tests

      - name: Install dependencies
        run: |
          export HOMEBREW_NO_AUTO_UPDATE=1
          export HOMEBREW_NO_INSTALL_CLEANUP=1
          brew install \
            cmake \
            coreutils \
            llvm@19 \
            lld@19
          export PIP_BREAK_SYSTEM_PACKAGES=1
          pip3 install -r nxdk_vsh_tests/requirements.txt

      - name: Prewarm nxdk
        working-directory: nxdk_vsh_tests
        run: |
          export PATH="$(brew --prefix llvm@19)/bin:$(brew --prefix lld@19)/bin:$PATH"
          export LDFLAGS="-L/opt/homebrew/opt/llvm@19/lib/c++ -L/opt/homebrew/opt/llvm@19/lib -L/opt/homebrew/opt/lld@19/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/lld@19/include"
          clang --version
          bash ${GITHUB_WORKSPACE}/nxdk_vsh_tests/prewarm-nxdk.sh --clean

      - name: Compile in dump mode
        run: |
          cd nxdk_vsh_tests
          # The default clang install will result in linker failures on macOS.
          export PATH="$(brew --prefix llvm@19)/bin:$(brew --prefix lld@19)/bin:$PATH"
          export LDFLAGS="-L/opt/homebrew/opt/llvm@19/lib/c++ -L/opt/homebrew/opt/llvm@19/lib -L/opt/homebrew/opt/lld@19/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/lld@19/include"
          export NXDK_DIR="${GITHUB_WORKSPACE}/nxdk_vsh_tests/third_party/nxdk"
          cmake -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_TOOLCHAIN_FILE="${NXDK_DIR}/share/toolchain-nxdk.cmake" \
                -DDUMP_CONFIG_FILE=ON
          cmake --build build -- -j

      - name: Compile in run mode
        run: |
          cd nxdk_vsh_tests
          # The default clang install will result in linker failures on macOS.
          export PATH="$(brew --prefix llvm@19)/bin:$(brew --prefix lld@19)/bin:$PATH"
          export LDFLAGS="-L/opt/homebrew/opt/llvm@19/lib/c++ -L/opt/homebrew/opt/llvm@19/lib -L/opt/homebrew/opt/lld@19/lib"
          export CPPFLAGS="-I/opt/homebrew/opt/lld@19/include"
          export NXDK_DIR="${GITHUB_WORKSPACE}/nxdk_vsh_tests/third_party/nxdk"
          cmake -B build \
                -DCMAKE_BUILD_TYPE=Release \
                -DCMAKE_TOOLCHAIN_FILE="${NXDK_DIR}/share/toolchain-nxdk.cmake" \
                -DDUMP_CONFIG_FILE=OFF
          cmake --build build -- -j
